name: CI/CD

on: [push] # tells github to run this on any push to the repository

jobs:
  test: # names the job
    runs-on: ubuntu-latest # sets the version of linux we want to use, should be what you have on your server

    strategy:
      fail-fast: false # tells github to not run further steps if this one fails

    steps:
      - uses: actions/checkout@v2 # fetches your commit to test it
        env:
          CI: true # shows terminal output!

  deploy:
    runs-on: ubuntu
    needs: test # this job depends on "test" having finished
    if: github.ref == 'refs/heads/uat' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploying to AWS Server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/codedeploy # we move into our app's folder
            git pull # we pull any changes from git
            #npm prune # we remove any unused dependencies
            #npm install # we install any missing dependencies
            #npm run build # we build our app
            #pm2 reload all # we reload the app via PM2
